name: "Salient Dream"
description: "All Things Strange"
signature: "Greetings, and welcome to my realm"
pygments: true
permalink: pretty
markdown: redcarpet
github:
  # enables "edit" link
  repo: 'rodyaj/rodyaj.github.io'
  branch: master
prose:
  siteurl: 'http://rodyaj.github.io'
  relativeLinks: 'http://rodyajgithub.io/links.jsonp'
  # uncomment to limit editing to the _posts directory
  #rooturl: '_posts'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Linux"
              value: "linux"
            - name: "Recipes"
              value: "recipes"
            - name: "Programming"
              value: "programming"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
